### ISSUE TITLE
Ability to configure plugin from resharper

### ISSUE THREAD

**Issue by blowin** [MO2k4/CleanCode#58]
There is no way to specify other limits for the number of lines in a method, and so on. I would like to be able to edit them directly in resharper.

**Comment by tomasKosar** [comment]
I think this is s bug maybe? Clean Code page in ReSharper -> Options does not work.

Based on
"The limits used by each analysis are configurable in the options page."

**Comment by jakub85** [comment]
Same issue here, having latest versions of R# and CleanCode plugin

**Comment by Mike-E-angelo** [comment]
Visited here for this issue.  This is what I see when attempting to visit the options page.

![](https://i.imgur.com/Ju0mynX.gif)

Maybe this project needs yet another fork. :P

**Comment by MO2k4** [comment]
sorry for the late response :-(

i am very open to pull requests at this end, because i was only upgrading this extension and had trouble in the past to get the dialogue working correctly :-(

in rider it works now as expected and i will publish a new release after the pipelines are going through and after that i need to wait for approval by Jetbrains.

**Comment by MO2k4** [comment]
The new version is now available, could someone confirm that it is working in r# too?

**Comment by tomasKosar** [comment]
Works for me in both ReSharper and Rider. Thanks!
